http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s

jwt:
  accessTokenTTL: 43200m
  refreshTokenTTL: 86400m
  signingKey: test

logger:
  level: 5
  fileName: ../../pkg/logger/logger.json
  maxSize: 5
  maxBackups: 3
  maxAge: 30

postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: zxc13243546
  dbname: banners_db
  sslmode: disabled
  maxIdleConnections: 5
  maxOpenConnections: 20
  connectionMaxLifetime: 60s
  driverName: postgres